# Generated by Django 5.2.4 on 2025-08-15 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aprendices", "0006_remove_aprendiz_programa_delete_excusa"),
        ("programas", "0004_programa_nivel_formacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Excusa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_excusa",
                    models.CharField(
                        choices=[
                            ("Medica", "Médica"),
                            ("Laboral", "Laboral"),
                            ("Personal", "Personal"),
                            ("Otro", "Otro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("motivo", models.TextField()),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("Recibida", "Recibida"),
                            ("No Recibida", "No Recibida"),
                        ],
                        default="Pendiente",
                        max_length=50,
                    ),
                ),
                (
                    "archivo_adjunto",
                    models.FileField(
                        blank=True, null=True, upload_to="excusas_adjuntos/"
                    ),
                ),
                (
                    "aprendiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aprendices.aprendiz",
                    ),
                ),
                (
                    "programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="programas.programa",
                    ),
                ),
            ],
        ),
    ]
