# Generated by Django 5.2.4 on 2025-07-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aprendices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aprendiz",
            name="ciudad",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="aprendiz",
            name="correo",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="aprendiz",
            name="documento_identidad",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="aprendiz",
            name="telefono",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
