# Generated by Django 5.2.4 on 2025-08-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aprendices", "0003_aprendizcurso_curso_aprendizcurso_curso_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aprendiz",
            options={
                "ordering": ["apellido", "nombre"],
                "verbose_name": "Aprendiz",
                "verbose_name_plural": "Aprendices",
            },
        ),
    ]
