# Generated by Django 5.2.4 on 2025-08-11 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aprendices", "0004_alter_aprendiz_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Excusa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_excusa",
                    models.CharField(
                        choices=[
                            ("Médica", "Médica"),
                            ("Laboral", "Laboral"),
                            ("Personal", "Personal"),
                            ("Otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "motivo",
                    models.TextField(
                        help_text="Motivo general de la excusa, ej: 'Tengo una cita médica'."
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("Recibido", "Recibido"),
                            ("No Recibido", "No Recibido"),
                        ],
                        default="Pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "aprendiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excusas",
                        to="aprendices.aprendiz",
                    ),
                ),
            ],
        ),
    ]
