# Generated by Django 5.2.4 on 2025-08-15 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aprendices", "0005_excusa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aprendiz",
            name="programa",
        ),
        migrations.DeleteModel(
            name="Excusa",
        ),
    ]
