# Generated by Django 5.2.4 on 2025-08-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="programas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre_del_Programa", models.CharField(max_length=100, unique=True)),
                ("Ficha_del_programa", models.CharField(max_length=100, unique=True)),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_finalizacion", models.DateTimeField(null=True)),
            ],
        ),
    ]
