# Generated by Django 5.2.4 on 2025-08-01 16:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre del Programa"
                    ),
                ),
                (
                    "ficha",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Ficha del Programa"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Inicio",
                    ),
                ),
                (
                    "fecha_finalizacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Finalización"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="programas",
        ),
    ]
