# Generated by Django 5.2.4 on 2025-08-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programas", "0002_programa_delete_programas"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programa",
            options={"ordering": ["nombre"], "verbose_name_plural": "Programas"},
        ),
        migrations.AlterField(
            model_name="programa",
            name="fecha_inicio",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Inicio"
            ),
        ),
    ]
