# Generated by Django 5.2.4 on 2025-08-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programas", "0003_alter_programa_options_alter_programa_fecha_inicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="programa",
            name="nivel_formacion",
            field=models.CharField(
                choices=[
                    ("Tecnologo", "Tecnólogo"),
                    ("Tecnico", "Técnico"),
                    ("Especializacion", "Especialización Tecnológica"),
                ],
                default="Tecnologo",
                max_length=20,
                verbose_name="Nivel de Formación",
            ),
        ),
    ]
